/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FileMeta = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'subjectId' : IDL.Opt(IDL.Text),
  'uploadedAt' : IDL.Int,
});
export const StudyMaterial = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
  'subjectId' : IDL.Opt(IDL.Text),
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'subjectId' : IDL.Opt(IDL.Text),
  'priority' : Priority,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Int, Priority],
      [IDL.Text],
      [],
    ),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteMaterial' : IDL.Func([IDL.Text], [], []),
  'deleteSubject' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFiles' : IDL.Func([], [IDL.Vec(FileMeta)], ['query']),
  'getFilesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(FileMeta)], ['query']),
  'getMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
  'getMaterialsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudyMaterial)],
      ['query'],
    ),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getUpcomingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMaterial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
      [StudyMaterial],
      [],
    ),
  'updateSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Subject], []),
  'updateTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Int,
        Priority,
        IDL.Bool,
      ],
      [Task],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FileMeta = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'subjectId' : IDL.Opt(IDL.Text),
    'uploadedAt' : IDL.Int,
  });
  const StudyMaterial = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
    'subjectId' : IDL.Opt(IDL.Text),
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'subjectId' : IDL.Opt(IDL.Text),
    'priority' : Priority,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Int, Priority],
        [IDL.Text],
        [],
      ),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteMaterial' : IDL.Func([IDL.Text], [], []),
    'deleteSubject' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFiles' : IDL.Func([], [IDL.Vec(FileMeta)], ['query']),
    'getFilesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(FileMeta)], ['query']),
    'getMaterials' : IDL.Func([], [IDL.Vec(StudyMaterial)], ['query']),
    'getMaterialsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudyMaterial)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getUpcomingTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMaterial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
        [StudyMaterial],
        [],
      ),
    'updateSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Subject], []),
    'updateTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Int,
          Priority,
          IDL.Bool,
        ],
        [Task],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };