/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FileMeta {
  'id' : string,
  'blob' : ExternalBlob,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : string,
  'subjectId' : [] | [string],
  'uploadedAt' : bigint,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface StudyMaterial {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'updatedAt' : bigint,
  'subjectId' : [] | [string],
}
export interface Subject {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
}
export interface Task {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'completed' : boolean,
  'dueDate' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'subjectId' : [] | [string],
  'priority' : Priority,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFile' : ActorMethod<
    [string, string, bigint, [] | [string], ExternalBlob],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMaterial' : ActorMethod<
    [string, string, [] | [string], Array<string>],
    string
  >,
  'createSubject' : ActorMethod<[string, string], string>,
  'createTask' : ActorMethod<
    [string, string, [] | [string], bigint, Priority],
    string
  >,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteMaterial' : ActorMethod<[string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFiles' : ActorMethod<[], Array<FileMeta>>,
  'getFilesBySubject' : ActorMethod<[string], Array<FileMeta>>,
  'getMaterials' : ActorMethod<[], Array<StudyMaterial>>,
  'getMaterialsBySubject' : ActorMethod<[string], Array<StudyMaterial>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksBySubject' : ActorMethod<[string], Array<Task>>,
  'getUpcomingTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMaterial' : ActorMethod<
    [string, string, string, [] | [string], Array<string>],
    StudyMaterial
  >,
  'updateSubject' : ActorMethod<[string, string, string], Subject>,
  'updateTask' : ActorMethod<
    [string, string, string, [] | [string], bigint, Priority, boolean],
    Task
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];